"""Fail-closed runtime controls stored on one dedicated GitHub Issue."""

from __future__ import annotations

import json
import os
import subprocess
import sys
from typing import Any, Iterable


CONTROL_ISSUE_TITLE = "[agent-control] Orchestrator controls"
CONTROL_MARKER = "<!-- agent-orchestrator-control:v1 -->"
CONTROL_LABEL = "agent-control"
ORCHESTRATOR_ENABLED_LABEL = "agent-orchestrator-enabled"
AUTO_MERGE_ENABLED_LABEL = "agent-auto-merge-enabled"
EMERGENCY_STOP_LABEL = "agent-emergency-stop"

# This is the single required-label contract.  setup_labels.py is only a
# compatibility entry point and imports this mapping; it must not evolve a
# second label dictionary.
REQUIRED_LABELS = {
    "agent-draft": {"color": "ededed", "description": "Task is in draft state"},
    "agent-ready": {"color": "0e8a16", "description": "Task is ready for implementation"},
    "agent-running": {"color": "fbca04", "description": "Implementation worker is active"},
    "ci-repairing": {"color": "d93f0b", "description": "CI repair worker is active"},
    "review-running": {"color": "1d76db", "description": "Review worker is active"},
    "review-passed": {"color": "0e8a16", "description": "Review passed, ready for merge"},
    "agent-review-blocked": {"color": "e11d48", "description": "Review requires operator inspection or retry"},
    "agent-merge-ready": {"color": "0e8a16", "description": "Exact-head review passed and awaits authorized merge"},
    "agent-blocked": {"color": "e11d48", "description": "Task is blocked"},
    "agent-complete": {"color": "0e8a16", "description": "Task completed and merged"},
    "agent-generated": {"color": "c5def5", "description": "Generated by agent-orchestrator"},
    CONTROL_LABEL: {"color": "5319e7", "description": "Identity label for the orchestrator control Issue"},
    ORCHESTRATOR_ENABLED_LABEL: {"color": "0e8a16", "description": "Allows orchestrator work when emergency stop is absent"},
    AUTO_MERGE_ENABLED_LABEL: {"color": "0e8a16", "description": "Allows merge after all independent gates pass"},
    EMERGENCY_STOP_LABEL: {"color": "e11d48", "description": "Stops all orchestrator transitions immediately"},
}
CONTROL_LABELS = frozenset({CONTROL_LABEL, ORCHESTRATOR_ENABLED_LABEL, AUTO_MERGE_ENABLED_LABEL, EMERGENCY_STOP_LABEL})


class ControlStateError(RuntimeError):
    """Raised when control authority is unavailable or ambiguous."""


def _repo() -> str:
    repo = os.environ.get("AGENT_REPO") or os.environ.get("GITHUB_REPOSITORY")
    if not repo:
        raise ControlStateError("GITHUB_REPOSITORY is unavailable")
    return repo


def _run_gh(*args: str, input_text: str | None = None) -> str:
    result = subprocess.run(
        ["gh", *args],
        input=input_text,
        capture_output=True,
        text=True,
        timeout=30,
    )
    if result.returncode != 0:
        raise ControlStateError(result.stderr.strip() or "GitHub control operation failed")
    return result.stdout.strip()


def _issue_labels(issue: dict[str, Any]) -> set[str]:
    labels = issue.get("labels", [])
    if not isinstance(labels, list):
        raise ControlStateError("agent-control Issue labels are malformed")
    names: set[str] = set()
    for label in labels:
        if not isinstance(label, dict) or not isinstance(label.get("name"), str) or not label["name"]:
            raise ControlStateError("agent-control Issue labels are malformed")
        names.add(label["name"])
    return names


def _decode_pages(raw: str, description: str) -> list[dict[str, Any]]:
    """Decode gh --paginate output, including slurped and line-delimited pages."""
    try:
        value = json.loads(raw)
    except json.JSONDecodeError:
        pages = []
        try:
            pages = [json.loads(line) for line in raw.splitlines() if line.strip()]
        except json.JSONDecodeError as exc:
            raise ControlStateError(description) from exc
        value = pages
    if isinstance(value, list) and all(isinstance(item, dict) for item in value):
        return value
    if isinstance(value, list) and all(isinstance(item, list) for item in value):
        flattened = [item for page in value for item in page]
        if all(isinstance(item, dict) for item in flattened):
            return flattened
    raise ControlStateError(description)


def resolve_control_issue(issues: Iterable[dict[str, Any]]) -> dict[str, Any]:
    """Return the one valid open control Issue, otherwise fail closed.

    The caller supplies the complete set of open Issues bearing the identity
    label.  Any malformed or ambiguous candidate is an authority failure.
    """

    candidates = list(issues)
    if len(candidates) != 1 or candidates[0].get("state") != "open":
        raise ControlStateError("exactly one open agent-control Issue is required")
    issue = candidates[0]
    labels = _issue_labels(issue)
    if (
        issue.get("title") != CONTROL_ISSUE_TITLE
        or CONTROL_MARKER not in str(issue.get("body") or "")
        or CONTROL_LABEL not in labels
        or not isinstance(issue.get("number"), int)
    ):
        raise ControlStateError("agent-control Issue is malformed")

    emergency_stop = EMERGENCY_STOP_LABEL in labels
    orchestrator_enabled = ORCHESTRATOR_ENABLED_LABEL in labels and not emergency_stop
    auto_merge_enabled = orchestrator_enabled and AUTO_MERGE_ENABLED_LABEL in labels
    return {
        "number": issue["number"],
        "title": CONTROL_ISSUE_TITLE,
        "labels": sorted(labels),
        "orchestrator_enabled": orchestrator_enabled,
        "auto_merge_enabled": auto_merge_enabled,
        "emergency_stop": emergency_stop,
    }


def read_control_state(repo: str | None = None) -> dict[str, Any]:
    target = repo or _repo()
    raw = _run_gh(
        "api",
        "--paginate",
        "--slurp",
        f"repos/{target}/issues?state=all&labels={CONTROL_LABEL}&per_page=100",
    )
    issues = _decode_pages(raw, "agent-control Issue response was invalid")
    return resolve_control_issue(issues)


def require_live(repo: str | None = None) -> dict[str, Any]:
    state = read_control_state(repo)
    if state["emergency_stop"]:
        raise ControlStateError("agent control emergency stop is active")
    if not state["orchestrator_enabled"]:
        raise ControlStateError("agent orchestrator is disabled")
    return state


def require_auto_merge(repo: str | None = None) -> dict[str, Any]:
    state = require_live(repo)
    if not state["auto_merge_enabled"]:
        raise ControlStateError("agent auto-merge is disabled")
    return state


def _list_labels(repo: str) -> dict[str, dict[str, Any]]:
    try:
        raw = _run_gh("label", "list", "--repo", repo, "--limit", "1000", "--json", "name,color,description")
        items = _decode_pages(raw, "unable to inspect repository labels")
    except ControlStateError:
        raise
    except Exception as exc:
        raise ControlStateError("unable to inspect repository labels") from exc
    existing: dict[str, dict[str, Any]] = {}
    for item in items:
        name = item.get("name")
        if not isinstance(name, str) or not name:
            raise ControlStateError("repository label response is malformed")
        existing[name] = item
    return existing


def _ensure_required_labels(repo: str) -> None:
    existing = _list_labels(repo)
    for name, props in REQUIRED_LABELS.items():
        if name not in existing:
            _run_gh(
                "label", "create", name, "--repo", repo,
                "--color", props["color"], "--description", props["description"],
            )
    final = _list_labels(repo)
    missing = sorted(set(REQUIRED_LABELS) - set(final))
    if missing:
        raise ControlStateError(f"required labels are missing after setup: {missing}")


def _edit_issue_labels(repo: str, number: int, add: Iterable[str], remove: Iterable[str]) -> None:
    args = ["issue", "edit", str(number), "--repo", repo]
    add = list(add)
    remove = list(remove)
    if add:
        args.extend(["--add-label", ",".join(add)])
    if remove:
        args.extend(["--remove-label", ",".join(remove)])
    if add or remove:
        _run_gh(*args)


def setup(repo: str | None = None) -> dict[str, Any]:
    """Idempotently create the control labels and one disabled control Issue."""

    target = repo or _repo()
    _ensure_required_labels(target)

    raw = _run_gh(
        "api",
        "--paginate",
        "--slurp",
        f"repos/{target}/issues?state=all&labels={CONTROL_LABEL}&per_page=100",
    )
    issues = _decode_pages(raw, "agent-control Issue response was invalid")
    if not issues:
        _run_gh(
            "issue",
            "create",
            "--repo",
            target,
            "--title",
            CONTROL_ISSUE_TITLE,
            "--body",
            f"{CONTROL_MARKER}\n\nLabels on this Issue are the live orchestrator controls.",
            "--label",
            f"{CONTROL_LABEL},{EMERGENCY_STOP_LABEL}",
        )
    state = read_control_state(target)
    expected_add = []
    expected_remove = [ORCHESTRATOR_ENABLED_LABEL, AUTO_MERGE_ENABLED_LABEL]
    if EMERGENCY_STOP_LABEL not in state["labels"]:
        expected_add.append(EMERGENCY_STOP_LABEL)
    mutation_error: ControlStateError | None = None
    if expected_add or any(label in state["labels"] for label in expected_remove):
        try:
            _edit_issue_labels(target, int(state["number"]), expected_add, expected_remove)
        except ControlStateError as exc:
            # A provider can report an error after applying the label edit.
            # The final live read is authoritative when it has converged to
            # the safe stopped state; otherwise preserve the failure.
            mutation_error = exc
    final = read_control_state(target)
    if not final["emergency_stop"] or final["orchestrator_enabled"] or final["auto_merge_enabled"]:
        if mutation_error is not None:
            raise mutation_error
        raise ControlStateError("control setup did not leave the Issue disabled and emergency-stopped")
    return final


def _transition_is_valid(command: str, state: dict[str, Any]) -> bool:
    expected = {
        "emergency-stop": (True, False, False),
        "emergency-resume": (False, False, False),
        "enable-orchestrator": (False, True, False),
        "disable-orchestrator": (state["emergency_stop"], False, False),
        "enable-auto-merge": (False, True, True),
        "disable-auto-merge": (state["emergency_stop"], state["orchestrator_enabled"], False),
    }
    if command not in expected:
        return False
    stop, orchestrator, auto_merge = expected[command]
    return (
        state["emergency_stop"] == stop
        and state["orchestrator_enabled"] == orchestrator
        and state["auto_merge_enabled"] == auto_merge
    )


def _compensate_labels(repo: str, number: int, before: dict[str, Any], after: dict[str, Any]) -> None:
    before_labels = set(before.get("labels", [])) & CONTROL_LABELS
    after_labels = set(after.get("labels", [])) & CONTROL_LABELS
    _edit_issue_labels(repo, number, before_labels - after_labels, after_labels - before_labels)


def _force_emergency_stop(repo: str, number: int) -> dict[str, Any]:
    """Converge to the safe stop state after a partial provider mutation."""

    _edit_issue_labels(
        repo, number, [EMERGENCY_STOP_LABEL],
        [ORCHESTRATOR_ENABLED_LABEL, AUTO_MERGE_ENABLED_LABEL],
    )
    observed = read_control_state(repo)
    if not _transition_is_valid("emergency-stop", observed):
        raise ControlStateError("emergency-stop compensation did not converge to a safe state")
    return observed


def mutate_control_labels(command: str, repo: str | None = None) -> dict[str, Any]:
    target = repo or _repo()
    state = read_control_state(target)
    number = str(state["number"])
    if command == "enable-orchestrator":
        if state["emergency_stop"]:
            raise ControlStateError("cannot enable orchestrator while emergency stop is active")
        if AUTO_MERGE_ENABLED_LABEL in state["labels"]:
            raise ControlStateError("control state has auto-merge enabled before orchestrator authorization")
        add, remove = [ORCHESTRATOR_ENABLED_LABEL], []
    elif command == "disable-orchestrator":
        add, remove = [], [ORCHESTRATOR_ENABLED_LABEL, AUTO_MERGE_ENABLED_LABEL]
    elif command == "enable-auto-merge":
        if state["emergency_stop"]:
            raise ControlStateError("cannot enable auto-merge while emergency stop is active")
        if not state["orchestrator_enabled"]:
            raise ControlStateError("cannot enable auto-merge while orchestrator is disabled")
        add, remove = [AUTO_MERGE_ENABLED_LABEL], []
    elif command == "disable-auto-merge":
        add, remove = [], [AUTO_MERGE_ENABLED_LABEL]
    elif command == "emergency-stop":
        add, remove = [EMERGENCY_STOP_LABEL], [ORCHESTRATOR_ENABLED_LABEL, AUTO_MERGE_ENABLED_LABEL]
    elif command == "emergency-resume":
        add, remove = [], [EMERGENCY_STOP_LABEL]
    else:
        raise ControlStateError(f"unknown control command: {command}")
    try:
        _edit_issue_labels(target, int(number), add, remove)
    except ControlStateError as mutation_error:
        # A provider can report an error after applying a mutation.  Reread
        # before deciding whether the command failed, rather than trusting the
        # CLI exit status alone.
        try:
            observed = read_control_state(target)
        except ControlStateError:
            raise mutation_error
        if _transition_is_valid(command, observed):
            return observed
        if command == "emergency-stop":
            return _force_emergency_stop(target, int(number))
        raise mutation_error
    observed = read_control_state(target)
    if not _transition_is_valid(command, observed):
        if command == "emergency-stop":
            return _force_emergency_stop(target, int(number))
        try:
            _compensate_labels(target, int(number), state, observed)
        except ControlStateError as compensation_error:
            raise ControlStateError(
                f"post-mutation control state mismatch; compensation failed: {compensation_error}"
            ) from compensation_error
        raise ControlStateError("post-mutation control state mismatch")
    return observed


def main() -> None:
    if len(sys.argv) < 2:
        print(
            "Usage: control_state.py <setup|setup-controls|status|read|require-live|require-auto-merge|"
            "enable-orchestrator|disable-orchestrator|enable-auto-merge|disable-auto-merge|"
            "emergency-stop|emergency-resume> [--repo OWNER/REPO]",
            file=sys.stderr,
        )
        raise SystemExit(2)
    command, arguments = sys.argv[1], sys.argv[2:]
    if len(arguments) == 0:
        repo = None
    elif len(arguments) == 1 and not arguments[0].startswith("-"):
        repo = arguments[0]
    elif len(arguments) == 2 and arguments[0] == "--repo":
        repo = arguments[1]
    else:
        print("invalid repository argument", file=sys.stderr)
        raise SystemExit(2)
    try:
        if command in {"setup", "setup-controls"}:
            state = setup(repo)
        elif command in {"status", "read"}:
            state = read_control_state(repo)
        elif command == "require-live":
            state = require_live(repo)
        elif command == "require-auto-merge":
            state = require_auto_merge(repo)
        else:
            state = mutate_control_labels(command, repo)
        print(json.dumps(state, sort_keys=True))
    except ControlStateError as exc:
        print(f"CONTROL_STATE_ERROR: {exc}", file=sys.stderr)
        raise SystemExit(1) from exc


if __name__ == "__main__":
    main()
