#!/usr/bin/env python3
"""Label initialization for the agent orchestrator.

Ensures all required labels exist before activation.
Safe to rerun; does not overwrite unrelated label metadata.

Usage:
  python3 setup_labels.py [--repo OWNER/REPO]
"""

import json
import os
import subprocess
import sys

GH = os.environ.get("AGENT_GH_CMD", "gh")

REQUIRED_LABELS = {
    "agent-draft": {"color": "ededed", "description": "Task is in draft state"},
    "agent-ready": {"color": "0e8a16", "description": "Task is ready for implementation"},
    "agent-running": {"color": "fbca04", "description": "Implementation worker is active"},
    "ci-repairing": {"color": "d93f0b", "description": "CI repair worker is active"},
    "review-running": {"color": "1d76db", "description": "Review worker is active"},
    "review-passed": {"color": "0e8a16", "description": "Review passed, ready for merge"},
    "agent-blocked": {"color": "e11d48", "description": "Task is blocked"},
    "agent-complete": {"color": "0e8a16", "description": "Task completed and merged"},
    "agent-generated": {"color": "c5def5", "description": "Generated by agent-orchestrator"},
    "agent-control": {"color": "5319e7", "description": "Identity label for the orchestrator control Issue"},
    "agent-orchestrator-enabled": {"color": "0e8a16", "description": "Allows orchestrator work when emergency stop is absent"},
    "agent-auto-merge-enabled": {"color": "0e8a16", "description": "Allows merge after all independent gates pass"},
    "agent-emergency-stop": {"color": "e11d48", "description": "Stops all orchestrator transitions immediately"},
}


def _gh(*args, repo=None):
    cmd = [GH] + list(args)
    if repo:
        cmd.extend(["--repo", repo])
    result = subprocess.run(cmd, capture_output=True, text=True, timeout=30)
    return result.returncode == 0, result.stdout.strip(), result.stderr.strip()


def get_existing_labels(repo=None):
    ok, stdout, stderr = _gh("label", "list", "--json", "name,color,description", repo=repo)
    if not ok:
        return {}
    try:
        labels = json.loads(stdout)
        return {lbl["name"]: lbl for lbl in labels}
    except (json.JSONDecodeError, KeyError):
        return {}


def create_or_update_label(name, color, description, existing, repo=None):
    if name in existing:
        existing_color = existing[name].get("color", "")
        existing_desc = existing[name].get("description", "")
        if existing_color == color and existing_desc == description:
            print(f"  [OK] {name} (already correct)")
            return True
        ok, _, stderr = _gh("label", "edit", name, "--color", color, "--description", description, repo=repo)
        if ok:
            print(f"  [UPDATED] {name}")
            return True
        else:
            print(f"  [WARN] {name} update failed: {stderr}")
            return False
    else:
        ok, _, stderr = _gh("label", "create", name, "--color", color, "--description", description, repo=repo)
        if ok:
            print(f"  [CREATED] {name}")
            return True
        else:
            print(f"  [WARN] {name} creation failed: {stderr}")
            return False


def main():
    repo = None
    for i, arg in enumerate(sys.argv[1:], 1):
        if arg == "--repo" and i < len(sys.argv) - 1:
            repo = sys.argv[i + 1]

    print("=== Agent Orchestrator Label Setup ===")
    print(f"Repository: {repo or '(current)'}")
    print()

    existing = get_existing_labels(repo)
    print(f"Found {len(existing)} existing labels")
    print()

    success = 0
    for name, props in REQUIRED_LABELS.items():
        if create_or_update_label(name, props["color"], props["description"], existing, repo):
            success += 1

    print()
    print(f"=== Results: {success}/{len(REQUIRED_LABELS)} labels configured ===")

    if success < len(REQUIRED_LABELS):
        sys.exit(1)


if __name__ == "__main__":
    main()
