"""Tests for worktree_manager.py (dry-run / logic tests only, no actual git ops)."""

import os
import sys
import unittest

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "scripts", "agent-control"))


class TestWorktreeManagerLogic(unittest.TestCase):

    def test_branch_naming(self):
        issue_number = 42
        branch = f"agent/issue-{issue_number}"
        self.assertEqual(branch, "agent/issue-42")

    def test_branch_naming_with_custom(self):
        custom_branch = "feature/my-feature"
        self.assertEqual(custom_branch, "feature/my-feature")

    def test_worktree_path(self):
        import pathlib
        import worktree_manager as wtm
        worktree_path = wtm.WORKTREE_BASE / "issue-42"
        self.assertEqual(worktree_path.name, "issue-42")
        self.assertTrue(str(worktree_path).endswith("issue-42"))
        self.assertTrue(str(worktree_path).startswith(str(wtm.WORKTREE_BASE)))

    def test_worktree_base_default(self):
        import worktree_manager as wtm
        self.assertEqual(str(wtm.WORKTREE_BASE), "/tmp/agent-worktrees")

    def test_worktree_base_env(self):
        os.environ["AGENT_WORKTREE_BASE"] = "/custom/worktree/path"
        import importlib
        import worktree_manager
        importlib.reload(worktree_manager)
        self.assertEqual(str(worktree_manager.WORKTREE_BASE), "/custom/worktree/path")
        del os.environ["AGENT_WORKTREE_BASE"]

    def test_pr_body_generation(self):
        issue_number = 42
        body = f"Implements #{issue_number}\n\n_Generated by agent-orchestrator_"
        self.assertIn("#42", body)
        self.assertIn("agent-orchestrator", body)

    def test_cleanup_only_removes_stale(self):
        import worktree_manager
        # Logic test only: verify the function signature exists
        self.assertTrue(hasattr(worktree_manager, "cleanup_stale_worktrees"))

    def test_push_branch_validates(self):
        import worktree_manager
        # Logic test only: verify the function signature exists
        self.assertTrue(hasattr(worktree_manager, "push_branch"))

    def test_create_pr_validates(self):
        import worktree_manager
        # Logic test only: verify the function signature exists
        self.assertTrue(hasattr(worktree_manager, "create_pr"))


if __name__ == "__main__":
    unittest.main()
