#!/usr/bin/env python3
"""Generate SDK wire type stubs from wire_contract/v1 schemas."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
SCHEMA_DIR = ROOT / "wire_contract" / "v1"
TS_OUT = ROOT / "sdk" / "typescript" / "src" / "generated-wire-types.ts"
PY_OUT = ROOT / "sdk" / "python" / "src" / "agent_control_plane_sdk" / "wire_types.py"
RUST_OUT = ROOT / "engine" / "src" / "wire_types.rs"

SCHEMA_FILES = [
    "dispatch_request.schema.json",
    "task_analysis.schema.json",
    "dispatch_decision.schema.json",
    "execution_result.schema.json",
    "evaluation_result.schema.json",
    "dispatch_bundle.schema.json",
]


def load_schema(name: str) -> dict:
    return json.loads((SCHEMA_DIR / name).read_text(encoding="utf-8"))


def load_all_schemas() -> dict[str, dict]:
    return {name: load_schema(name) for name in SCHEMA_FILES}


def ts_union(values: list[str]) -> str:
    return " | ".join('"' + v + '"' for v in values)


def py_literal(values: list[str]) -> str:
    return "Literal[" + ", ".join('"' + v + '"' for v in values) + "]"


def schema_enum(schemas: dict[str, dict], name: str, *path: str) -> list[str]:
    value: Any = schemas[name]
    for segment in path:
        value = value[segment]
    return value["enum"]


def enum_values(schemas: dict[str, dict]) -> dict[str, list[str]]:
    return {
        "request_sources": schema_enum(
            schemas, "dispatch_request.schema.json", "properties", "request_source"
        ),
        "model_tiers": schema_enum(
            schemas, "dispatch_decision.schema.json", "$defs", "model_tier"
        ),
        "task_domains": schema_enum(
            schemas, "task_analysis.schema.json", "properties", "task_domain"
        ),
        "task_intents": schema_enum(
            schemas, "task_analysis.schema.json", "properties", "task_intent"
        ),
        "risk_flags": schema_enum(
            schemas, "task_analysis.schema.json", "properties", "risk_flags", "items"
        ),
        "quality_reqs": schema_enum(
            schemas, "task_analysis.schema.json", "properties", "quality_requirement"
        ),
        "risk_levels": schema_enum(
            schemas, "task_analysis.schema.json", "properties", "risk_level"
        ),
        "confidence_labels": schema_enum(
            schemas, "task_analysis.schema.json", "properties", "confidence_label"
        ),
        "evidence_polarities": schema_enum(
            schemas,
            "task_analysis.schema.json",
            "$defs",
            "evidence",
            "properties",
            "polarity",
        ),
        "evidence_sources": schema_enum(
            schemas,
            "task_analysis.schema.json",
            "$defs",
            "evidence",
            "properties",
            "source",
        ),
        "expected_quality_bands": schema_enum(
            schemas, "dispatch_decision.schema.json", "properties", "expected_quality_band"
        ),
        "decision_statuses": schema_enum(
            schemas, "dispatch_decision.schema.json", "properties", "decision_status"
        ),
        "gate_severities": schema_enum(
            schemas,
            "dispatch_decision.schema.json",
            "$defs",
            "execution_gate",
            "properties",
            "severity",
        ),
        "executor_types": schema_enum(
            schemas, "execution_result.schema.json", "properties", "executor_type"
        ),
        "execution_statuses": schema_enum(
            schemas, "execution_result.schema.json", "properties", "status"
        ),
        "evaluation_statuses": schema_enum(
            schemas, "evaluation_result.schema.json", "properties", "status"
        ),
        "check_statuses": schema_enum(
            schemas,
            "evaluation_result.schema.json",
            "$defs",
            "evaluation_check",
            "properties",
            "status",
        ),
        "final_statuses": schema_enum(
            schemas,
            "dispatch_bundle.schema.json",
            "$defs",
            "dispatch_record",
            "properties",
            "final_status",
        ),
    }


def render_ts(schemas: dict[str, dict]) -> str:
    lines: list[str] = []
    enums = enum_values(schemas)

    lines.append("// Generated by codegen/generate_wire_types.py. DO NOT EDIT.")
    lines.append("")
    lines.append("export type RequestSource = " + ts_union(enums["request_sources"]) + ";")
    lines.append("")
    lines.append("export type ModelTier = " + ts_union(enums["model_tiers"]) + ";")
    lines.append("export type TaskDomain = " + ts_union(enums["task_domains"]) + ";")
    lines.append("export type TaskIntent = " + ts_union(enums["task_intents"]) + ";")
    lines.append("export type RiskFlag = " + ts_union(enums["risk_flags"]) + ";")
    lines.append("export type QualityRequirement = " + ts_union(enums["quality_reqs"]) + ";")
    lines.append("export type RiskLevel = " + ts_union(enums["risk_levels"]) + ";")
    lines.append("export type ConfidenceLabel = " + ts_union(enums["confidence_labels"]) + ";")
    lines.append("export type EvidencePolarity = " + ts_union(enums["evidence_polarities"]) + ";")
    lines.append("export type EvidenceSource = " + ts_union(enums["evidence_sources"]) + ";")
    lines.append("export type ExpectedQualityBand = " + ts_union(enums["expected_quality_bands"]) + ";")
    lines.append("export type DecisionStatus = " + ts_union(enums["decision_statuses"]) + ";")
    lines.append("export type GateSeverity = " + ts_union(enums["gate_severities"]) + ";")
    lines.append("export type ExecutorType = " + ts_union(enums["executor_types"]) + ";")
    lines.append("export type ExecutionStatus = " + ts_union(enums["execution_statuses"]) + ";")
    lines.append("export type EvaluationStatus = " + ts_union(enums["evaluation_statuses"]) + ";")
    lines.append("export type CheckStatus = " + ts_union(enums["check_statuses"]) + ";")
    lines.append("export type FinalStatus = " + ts_union(enums["final_statuses"]) + ";")
    lines.append("")

    interfaces = [
        ("Evidence", ["feature: string;", "text: string;", "span: [number, number];", "polarity: EvidencePolarity;", "source: EvidenceSource;", "rule_id: string | null;", "confidence: number;", "negation_scope: string | null;"]),
        ("TaskAnalysis", ['schema_version: "task_analysis.v1";', "analysis_id: string;", "raw_request_snapshot: string;", "request_source: RequestSource;", "primary_task_type: string;", "task_domain: TaskDomain;", "task_intent: TaskIntent;", "risk_flags: RiskFlag[];", "complexity_score: number;", "cognitive_complexity: number;", "context_complexity: number;", "execution_risk: number;", "ambiguity_score: number;", "required_capabilities: string[];", "context_budget_estimate: number;", "execution_budget_estimate: number;", "quality_requirement: QualityRequirement;", "risk_level: RiskLevel;", "confidence: number;", "confidence_label: ConfidenceLabel;", "uncertainty_reason: string[];", "safe_default: string;", "escalation_trigger: string | null;", "positive_evidence: Evidence[];", "negative_evidence: Evidence[];", "features_detected: Record<string, unknown>;", 'analysis_method: "rule_only";', "created_at: string;"]),
        ("BudgetReservation", ['schema_version: "budget_reservation.v1";', "reservation_id: string;", "decision_id: string;", "currency: string;", "pricing_snapshot_id: string | null;", "pre_budget: number;", "reserved_input_tokens: number;", "reserved_output_tokens: number;", "reserved_total_tokens: number;", "reserved_cost: number;", "budget_policy_id: string | null;", "budget_gate: string | null;", "status: string;", "actual_usage_ref: string | null;", "budget_delta: number | null;", "budget_violation: boolean;", "created_at: string;", "updated_at: string;", "expires_at: string | null;"]),
        ("ExecutionGate", ["gate_id: string;", "gate_type: string;", "severity: GateSeverity;", "reason: string;", "evidence_refs: string[];", "clearance_required: string;", "cleared: boolean;", "cleared_by: string | null;", "cleared_at: string | null;"]),
        ("ShadowRoute", ["tier: ModelTier;", "profile_id: string | null;", "reason: string;", "admission_scope: string;", "estimated_cost: number | null;", "expected_tradeoff: string;"]),
        ("RejectedCandidate", ["tier: ModelTier;", "profile_id: string | null;", "reason: string;", "constraint_failed: string | null;", "estimated_cost: number | null;"]),
        ("DispatchDecision", ['schema_version: "dispatch_decision.v1";', "decision_id: string;", "analysis_id: string;", "analysis_snapshot: Record<string, unknown>;", "selected_tier: ModelTier;", "selected_profile_id: string | null;", "fallback_tier: ModelTier;", "fallback_profile_id: string | null;", "shadow_routes: ShadowRoute[];", "hard_constraints: string[];", "rejected_candidates: RejectedCandidate[];", "no_shadow_route_reason: string | null;", "max_input_tokens: number;", "max_output_tokens: number;", "routing_reason: string;", "quality_requirement: QualityRequirement;", "expected_quality_band: ExpectedQualityBand;", "confidence: number;", "confidence_label: ConfidenceLabel;", "budget_reservation: BudgetReservation;", "execution_policy: Record<string, unknown>;", "execution_gates: ExecutionGate[];", "routing_mode: string;", "routing_experiment_id: string | null;", "decision_status: DecisionStatus;", "created_at: string;"]),
        ("ExecutionResult", ['schema_version: "execution_result.v1";', "result_id: string;", "dispatch_id: string;", "decision_id: string;", "executor_type: ExecutorType;", "status: ExecutionStatus;", "output: string | null;", "prompt_pack: Record<string, unknown> | null;", "input_tokens: number | null;", "output_tokens: number | null;", "estimated_cost: number | null;", "latency_ms: number | null;", "error_domain: string | null;", "error_message: string | null;", "provider_request_id: string | null;", "attempt_number: number | null;", "finish_reason: string | null;", "usage_source: string | null;", "created_at: string;"]),
        ("EvaluationCheck", ["check_id: string;", "name: string;", "status: CheckStatus;", "reason: string;"]),
        ("EvaluationResult", ['schema_version: "evaluation_result.v1";', "evaluation_id: string;", "dispatch_id: string;", "decision_id: string;", "execution_result_id: string;", "status: EvaluationStatus;", "checks: EvaluationCheck[];", "quality_score: number | null;", "requires_retry: boolean;", "retry_reason: string | null;", "created_at: string;"]),
        ("DispatchRecord", ['schema_version: "dispatch_record.v1";', "dispatch_id: string;", "request_snapshot: string;", "task_analysis_id: string;", "decision_id: string;", "execution_result_id: string | null;", "evaluation_result_id: string | null;", "usage_ledger_row_id: string | null;", "budget_reservation_id: string | null;", "final_status: FinalStatus;", "created_at: string;", "updated_at: string;"]),
        ("DispatchBundle", ["record: DispatchRecord;", "analysis: TaskAnalysis;", "decision: DispatchDecision;", "execution_result: ExecutionResult;", "evaluation_result: EvaluationResult;"]),
        ("DispatchRequest", ['schema_version?: "dispatch_request.v1";', "raw_request: string;", "request_source: RequestSource;"]),
    ]

    for name, fields in interfaces:
        lines.append("export interface " + name + " {")
        for f in fields:
            lines.append("  " + f)
        lines.append("}")
        lines.append("")

    return "\n".join(lines)


def render_python(schemas: dict[str, dict]) -> str:
    lines: list[str] = []

    lines.append("from __future__ import annotations")
    lines.append("")
    lines.append("from dataclasses import dataclass")
    lines.append("from typing import Any, Literal, NotRequired, TypedDict")
    lines.append("")

    enums = enum_values(schemas)

    lines.append("RequestSource = " + py_literal(enums["request_sources"]))
    lines.append("")
    lines.append("ModelTier = " + py_literal(enums["model_tiers"]))
    lines.append("TaskDomain = " + py_literal(enums["task_domains"]))
    lines.append("TaskIntent = " + py_literal(enums["task_intents"]))
    lines.append("RiskFlag = " + py_literal(enums["risk_flags"]))
    lines.append("QualityRequirement = " + py_literal(enums["quality_reqs"]))
    lines.append("RiskLevel = " + py_literal(enums["risk_levels"]))
    lines.append("ConfidenceLabel = " + py_literal(enums["confidence_labels"]))
    lines.append("EvidencePolarity = " + py_literal(enums["evidence_polarities"]))
    lines.append("EvidenceSource = " + py_literal(enums["evidence_sources"]))
    lines.append("ExpectedQualityBand = " + py_literal(enums["expected_quality_bands"]))
    lines.append("DecisionStatus = " + py_literal(enums["decision_statuses"]))
    lines.append("GateSeverity = " + py_literal(enums["gate_severities"]))
    lines.append("ExecutorType = " + py_literal(enums["executor_types"]))
    lines.append("ExecutionStatus = " + py_literal(enums["execution_statuses"]))
    lines.append("EvaluationStatus = " + py_literal(enums["evaluation_statuses"]))
    lines.append("CheckStatus = " + py_literal(enums["check_statuses"]))
    lines.append("FinalStatus = " + py_literal(enums["final_statuses"]))
    lines.append("")

    lines.append("@dataclass(frozen=True)")
    lines.append("class DispatchRequest:")
    lines.append("    raw_request: str")
    lines.append('    request_source: RequestSource = "api"')
    lines.append('    schema_version: Literal["dispatch_request.v1"] = "dispatch_request.v1"')
    lines.append("")
    lines.append("    def to_json(self) -> dict[str, Any]:")
    lines.append("        return {")
    lines.append('            "schema_version": self.schema_version,')
    lines.append('            "raw_request": self.raw_request,')
    lines.append('            "request_source": self.request_source,')
    lines.append("        }")
    lines.append("")

    typed_dicts = [
        ("Evidence", [("feature", "str"), ("text", "str"), ("span", "tuple[int, int]"), ("polarity", "EvidencePolarity"), ("source", "EvidenceSource"), ("rule_id", "str | None"), ("confidence", "float"), ("negation_scope", "str | None")]),
        ("TaskAnalysis", [("schema_version", 'Literal["task_analysis.v1"]'), ("analysis_id", "str"), ("raw_request_snapshot", "str"), ("request_source", "RequestSource"), ("primary_task_type", "str"), ("task_domain", "TaskDomain"), ("task_intent", "TaskIntent"), ("risk_flags", "list[RiskFlag]"), ("complexity_score", "float"), ("cognitive_complexity", "float"), ("context_complexity", "float"), ("execution_risk", "float"), ("ambiguity_score", "float"), ("required_capabilities", "list[str]"), ("context_budget_estimate", "int"), ("execution_budget_estimate", "int"), ("quality_requirement", "QualityRequirement"), ("risk_level", "RiskLevel"), ("confidence", "float"), ("confidence_label", "ConfidenceLabel"), ("uncertainty_reason", "list[str]"), ("safe_default", "str"), ("escalation_trigger", "str | None"), ("positive_evidence", "list[Evidence]"), ("negative_evidence", "list[Evidence]"), ("features_detected", "dict[str, Any]"), ("analysis_method", 'Literal["rule_only"]'), ("created_at", "str")]),
        ("BudgetReservation", [("schema_version", 'Literal["budget_reservation.v1"]'), ("reservation_id", "str"), ("decision_id", "str"), ("currency", "str"), ("pricing_snapshot_id", "str | None"), ("pre_budget", "int"), ("reserved_input_tokens", "int"), ("reserved_output_tokens", "int"), ("reserved_total_tokens", "int"), ("reserved_cost", "float"), ("budget_policy_id", "str | None"), ("budget_gate", "str | None"), ("status", "str"), ("actual_usage_ref", "str | None"), ("budget_delta", "int | None"), ("budget_violation", "bool"), ("created_at", "str"), ("updated_at", "str"), ("expires_at", "str | None")]),
        ("ExecutionGate", [("gate_id", "str"), ("gate_type", "str"), ("severity", "GateSeverity"), ("reason", "str"), ("evidence_refs", "list[str]"), ("clearance_required", "str"), ("cleared", "bool"), ("cleared_by", "str | None"), ("cleared_at", "str | None")]),
        ("ShadowRoute", [("tier", "ModelTier"), ("profile_id", "str | None"), ("reason", "str"), ("admission_scope", "str"), ("estimated_cost", "float | None"), ("expected_tradeoff", "str")]),
        ("RejectedCandidate", [("tier", "ModelTier"), ("profile_id", "str | None"), ("reason", "str"), ("constraint_failed", "str | None"), ("estimated_cost", "float | None")]),
        ("DispatchDecision", [("schema_version", 'Literal["dispatch_decision.v1"]'), ("decision_id", "str"), ("analysis_id", "str"), ("analysis_snapshot", "dict[str, Any]"), ("selected_tier", "ModelTier"), ("selected_profile_id", "str | None"), ("fallback_tier", "ModelTier"), ("fallback_profile_id", "str | None"), ("shadow_routes", "list[ShadowRoute]"), ("hard_constraints", "list[str]"), ("rejected_candidates", "list[RejectedCandidate]"), ("no_shadow_route_reason", "str | None"), ("max_input_tokens", "int"), ("max_output_tokens", "int"), ("routing_reason", "str"), ("quality_requirement", "QualityRequirement"), ("expected_quality_band", "ExpectedQualityBand"), ("confidence", "float"), ("confidence_label", "ConfidenceLabel"), ("budget_reservation", "BudgetReservation"), ("execution_policy", "dict[str, Any]"), ("execution_gates", "list[ExecutionGate]"), ("routing_mode", "str"), ("routing_experiment_id", "str | None"), ("decision_status", "DecisionStatus"), ("created_at", "str")]),
        ("ExecutionResult", [("schema_version", 'Literal["execution_result.v1"]'), ("result_id", "str"), ("dispatch_id", "str"), ("decision_id", "str"), ("executor_type", "ExecutorType"), ("status", "ExecutionStatus"), ("output", "str | None"), ("prompt_pack", "dict[str, Any] | None"), ("input_tokens", "int | None"), ("output_tokens", "int | None"), ("estimated_cost", "float | None"), ("latency_ms", "int | None"), ("error_domain", "str | None"), ("error_message", "str | None"), ("provider_request_id", "str | None"), ("attempt_number", "int | None"), ("finish_reason", "str | None"), ("usage_source", "str | None"), ("created_at", "str")]),
        ("EvaluationCheck", [("check_id", "str"), ("name", "str"), ("status", "CheckStatus"), ("reason", "str")]),
        ("EvaluationResult", [("schema_version", 'Literal["evaluation_result.v1"]'), ("evaluation_id", "str"), ("dispatch_id", "str"), ("decision_id", "str"), ("execution_result_id", "str"), ("status", "EvaluationStatus"), ("checks", "list[EvaluationCheck]"), ("quality_score", "float | None"), ("requires_retry", "bool"), ("retry_reason", "str | None"), ("created_at", "str")]),
        ("DispatchRecord", [("schema_version", 'Literal["dispatch_record.v1"]'), ("dispatch_id", "str"), ("request_snapshot", "str"), ("task_analysis_id", "str"), ("decision_id", "str"), ("execution_result_id", "str | None"), ("evaluation_result_id", "str | None"), ("usage_ledger_row_id", "str | None"), ("budget_reservation_id", "str | None"), ("final_status", "FinalStatus"), ("created_at", "str"), ("updated_at", "str")]),
        ("DispatchBundle", [("record", "DispatchRecord"), ("analysis", "TaskAnalysis"), ("decision", "DispatchDecision"), ("execution_result", "ExecutionResult"), ("evaluation_result", "EvaluationResult")]),
        ("LocalTierCost", [("selected_tier", "str"), ("dispatch_count", "int"), ("reserved_cost", "float"), ("estimated_cost_usd", "float"), ("input_tokens", "int"), ("output_tokens", "int")]),
        ("LocalDailyCost", [("date", "str"), ("dispatch_count", "int"), ("reserved_cost", "float"), ("estimated_cost_usd", "float")]),
        ("LocalCostSummary", [("schema_version", 'Literal["local_cost_summary.v2"]'), ("currency", "str"), ("dispatch_count", "int"), ("total_reserved_cost", "float"), ("total_estimated_cost_usd", "float"), ("total_input_tokens", "int"), ("total_output_tokens", "int"), ("estimated_cost_available", "bool"), ("pricing_configured", "NotRequired[bool]"), ("cost_utilization", "float"), ("by_tier", "list[LocalTierCost]"), ("daily", "list[LocalDailyCost]")]),
        ("LocalDispatchCostRow", [("history_id", "int"), ("dispatch_id", "str"), ("created_at", "str"), ("selected_tier", "str"), ("reserved_cost", "float"), ("input_tokens", "int"), ("output_tokens", "int"), ("estimated_cost_usd", "float"), ("executor_type", "str"), ("latency_ms", "int | None")]),
        ("LocalDispatchCostDetail", [("schema_version", 'Literal["local_dispatch_cost_detail.v1"]'), ("dispatches", "list[LocalDispatchCostRow]")]),
        ("ApiStatus", [("schema_version", 'Literal["axum_api.v1"]'), ("status", "str"), ("tenant_id", "str")]),
    ]

    for name, fields in typed_dicts:
        if name == "ApiStatus":
            lines.append("class ApiStatus(TypedDict, total=False):")
        else:
            lines.append("class " + name + "(TypedDict):")
        for fname, ftype in fields:
            lines.append("    " + fname + ": " + ftype)
        lines.append("")

    return "\n".join(lines)


def snake_to_pascal(name: str) -> str:
    return "".join(part.capitalize() for part in name.split("_"))


def render_rust(schemas: dict[str, dict]) -> str:
    enums = enum_values(schemas)
    lines: list[str] = [
        "// Generated by codegen/generate_wire_types.py. DO NOT EDIT.",
        "",
        "use serde::{Deserialize, Serialize};",
        "use serde_json::Value;",
        "",
    ]

    enum_mappings = [
        ("RequestSource", enums["request_sources"]),
        ("ModelTier", enums["model_tiers"]),
        ("TaskDomain", enums["task_domains"]),
        ("TaskIntent", enums["task_intents"]),
        ("RiskFlag", enums["risk_flags"]),
        ("QualityRequirement", enums["quality_reqs"]),
        ("RiskLevel", enums["risk_levels"]),
        ("ConfidenceLabel", enums["confidence_labels"]),
        ("EvidencePolarity", enums["evidence_polarities"]),
        ("EvidenceSource", enums["evidence_sources"]),
        ("ExpectedQualityBand", enums["expected_quality_bands"]),
        ("DecisionStatus", enums["decision_statuses"]),
        ("GateSeverity", enums["gate_severities"]),
        ("ExecutorType", enums["executor_types"]),
        ("ExecutionStatus", enums["execution_statuses"]),
        ("EvaluationStatus", enums["evaluation_statuses"]),
        ("CheckStatus", enums["check_statuses"]),
        ("FinalStatus", enums["final_statuses"]),
    ]

    for enum_name, variants in enum_mappings:
        lines.append("#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq)]")
        lines.append('#[serde(rename_all = "snake_case")]')
        lines.append(f"pub enum {enum_name} {{")
        for v in variants:
            lines.append(f"    {snake_to_pascal(v)},")
        lines.append("}")
        lines.append("")

    structs = [
        (
            "Evidence",
            False,
            [
                ("feature", "String"),
                ("text", "String"),
                ("span", "(i64, i64)"),
                ("polarity", "EvidencePolarity"),
                ("source", "EvidenceSource"),
                ("rule_id", "Option<String>"),
                ("confidence", "f64"),
                ("negation_scope", "Option<String>"),
            ],
        ),
        (
            "TaskAnalysis",
            False,
            [
                ("schema_version", "String"),
                ("analysis_id", "String"),
                ("raw_request_snapshot", "String"),
                ("request_source", "RequestSource"),
                ("primary_task_type", "String"),
                ("task_domain", "TaskDomain"),
                ("task_intent", "TaskIntent"),
                ("risk_flags", "Vec<RiskFlag>"),
                ("complexity_score", "f64"),
                ("cognitive_complexity", "f64"),
                ("context_complexity", "f64"),
                ("execution_risk", "f64"),
                ("ambiguity_score", "f64"),
                ("required_capabilities", "Vec<String>"),
                ("context_budget_estimate", "i64"),
                ("execution_budget_estimate", "i64"),
                ("quality_requirement", "QualityRequirement"),
                ("risk_level", "RiskLevel"),
                ("confidence", "f64"),
                ("confidence_label", "ConfidenceLabel"),
                ("uncertainty_reason", "Vec<String>"),
                ("safe_default", "String"),
                ("escalation_trigger", "Option<String>"),
                ("positive_evidence", "Vec<Evidence>"),
                ("negative_evidence", "Vec<Evidence>"),
                ("features_detected", "Value"),
                ("analysis_method", "String"),
                ("created_at", "String"),
            ],
        ),
        (
            "BudgetReservation",
            False,
            [
                ("schema_version", "String"),
                ("reservation_id", "String"),
                ("decision_id", "String"),
                ("currency", "String"),
                ("pricing_snapshot_id", "Option<String>"),
                ("pre_budget", "i64"),
                ("reserved_input_tokens", "i64"),
                ("reserved_output_tokens", "i64"),
                ("reserved_total_tokens", "i64"),
                ("reserved_cost", "f64"),
                ("budget_policy_id", "Option<String>"),
                ("budget_gate", "Option<String>"),
                ("status", "String"),
                ("actual_usage_ref", "Option<String>"),
                ("budget_delta", "Option<i64>"),
                ("budget_violation", "bool"),
                ("created_at", "String"),
                ("updated_at", "String"),
                ("expires_at", "Option<String>"),
            ],
        ),
        (
            "ExecutionGate",
            True,
            [
                ("gate_id", "String"),
                ("gate_type", "String"),
                ("severity", "GateSeverity"),
                ("reason", "String"),
                ("evidence_refs", "Vec<String>"),
                ("clearance_required", "String"),
                ("cleared", "bool"),
                ("cleared_by", "Option<String>"),
                ("cleared_at", "Option<String>"),
            ],
        ),
        (
            "ShadowRoute",
            False,
            [
                ("tier", "ModelTier"),
                ("profile_id", "Option<String>"),
                ("reason", "String"),
                ("admission_scope", "String"),
                ("estimated_cost", "Option<f64>"),
                ("expected_tradeoff", "String"),
            ],
        ),
        (
            "RejectedCandidate",
            False,
            [
                ("tier", "ModelTier"),
                ("profile_id", "Option<String>"),
                ("reason", "String"),
                ("constraint_failed", "Option<String>"),
                ("estimated_cost", "Option<f64>"),
            ],
        ),
        (
            "DispatchDecision",
            False,
            [
                ("schema_version", "String"),
                ("decision_id", "String"),
                ("analysis_id", "String"),
                ("analysis_snapshot", "Value"),
                ("selected_tier", "ModelTier"),
                ("selected_profile_id", "Option<String>"),
                ("fallback_tier", "ModelTier"),
                ("fallback_profile_id", "Option<String>"),
                ("shadow_routes", "Vec<ShadowRoute>"),
                ("hard_constraints", "Vec<String>"),
                ("rejected_candidates", "Vec<RejectedCandidate>"),
                ("no_shadow_route_reason", "Option<String>"),
                ("max_input_tokens", "i64"),
                ("max_output_tokens", "i64"),
                ("routing_reason", "String"),
                ("quality_requirement", "QualityRequirement"),
                ("expected_quality_band", "ExpectedQualityBand"),
                ("confidence", "f64"),
                ("confidence_label", "ConfidenceLabel"),
                ("budget_reservation", "BudgetReservation"),
                ("execution_policy", "Value"),
                ("execution_gates", "Vec<ExecutionGate>"),
                ("routing_mode", "String"),
                ("routing_experiment_id", "Option<String>"),
                ("decision_status", "DecisionStatus"),
                ("created_at", "String"),
            ],
        ),
        (
            "ExecutionResult",
            False,
            [
                ("schema_version", "String"),
                ("result_id", "String"),
                ("dispatch_id", "String"),
                ("decision_id", "String"),
                ("executor_type", "ExecutorType"),
                ("status", "ExecutionStatus"),
                ("output", "Option<String>"),
                ("prompt_pack", "Option<Value>"),
                ("input_tokens", "Option<i64>"),
                ("output_tokens", "Option<i64>"),
                ("estimated_cost", "Option<f64>"),
                ("latency_ms", "Option<i64>"),
                ("error_domain", "Option<String>"),
                ("error_message", "Option<String>"),
                ("provider_request_id", "Option<String>"),
                ("attempt_number", "Option<i64>"),
                ("finish_reason", "Option<String>"),
                ("usage_source", "Option<String>"),
                ("created_at", "String"),
            ],
        ),
        (
            "EvaluationCheck",
            True,
            [
                ("check_id", "String"),
                ("name", "String"),
                ("status", "CheckStatus"),
                ("reason", "String"),
            ],
        ),
        (
            "EvaluationResult",
            False,
            [
                ("schema_version", "String"),
                ("evaluation_id", "String"),
                ("dispatch_id", "String"),
                ("decision_id", "String"),
                ("execution_result_id", "String"),
                ("status", "EvaluationStatus"),
                ("checks", "Vec<EvaluationCheck>"),
                ("quality_score", "Option<f64>"),
                ("requires_retry", "bool"),
                ("retry_reason", "Option<String>"),
                ("created_at", "String"),
            ],
        ),
        (
            "DispatchRecord",
            True,
            [
                ("schema_version", "String"),
                ("dispatch_id", "String"),
                ("request_snapshot", "String"),
                ("task_analysis_id", "String"),
                ("decision_id", "String"),
                ("execution_result_id", "Option<String>"),
                ("evaluation_result_id", "Option<String>"),
                ("usage_ledger_row_id", "Option<String>"),
                ("budget_reservation_id", "Option<String>"),
                ("final_status", "FinalStatus"),
                ("created_at", "String"),
                ("updated_at", "String"),
            ],
        ),
        (
            "DispatchBundle",
            False,
            [
                ("record", "DispatchRecord"),
                ("analysis", "TaskAnalysis"),
                ("decision", "DispatchDecision"),
                ("execution_result", "ExecutionResult"),
                ("evaluation_result", "EvaluationResult"),
            ],
        ),
        (
            "DispatchRequest",
            True,
            [
                ("schema_version", "String"),
                ("raw_request", "String"),
                ("request_source", "RequestSource"),
            ],
        ),
        (
            "DispatchBundleValue",
            False,
            [
                ("record", "Value"),
                ("analysis", "Value"),
                ("decision", "Value"),
                ("execution_result", "Value"),
                ("evaluation_result", "Value"),
            ],
        ),
        (
            "ApiStatus",
            False,
            [
                ("schema_version", "String"),
                ("status", "String"),
                ("tenant_id", "Option<String>"),
            ],
        ),
    ]

    for struct_name, is_eq, fields in structs:
        derive = (
            "#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq)]"
            if is_eq
            else "#[derive(Clone, Debug, Serialize, Deserialize, PartialEq)]"
        )
        lines.append(derive)
        lines.append(f"pub struct {struct_name} {{")
        for fname, ftype in fields:
            lines.append(f"    pub {fname}: {ftype},")
        lines.append("}")
        lines.append("")

    return "\n".join(lines)


def write_or_check(path: Path, content: str, check: bool) -> bool:
    relative_path = path.relative_to(ROOT)
    if check:
        if not path.exists() or path.read_text(encoding="utf-8") != content:
            print(f"drift detected: {relative_path}")
            return False
        print(f"checked {relative_path}")
        return True

    path.write_text(content, encoding="utf-8")
    print(f"wrote {relative_path} ({len(content)} bytes)")
    return True


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail instead of writing when generated outputs differ",
    )
    args = parser.parse_args()
    schemas = load_all_schemas()

    outputs = [
        (TS_OUT, render_ts(schemas)),
        (PY_OUT, render_python(schemas)),
        (RUST_OUT, render_rust(schemas)),
    ]
    results = [write_or_check(path, content, args.check) for path, content in outputs]
    return 0 if all(results) else 1


if __name__ == "__main__":
    raise SystemExit(main())
