"""Core primitives for the token-efficient agent harness."""

from .advisor import (
    AdvisorBroker,
    AdvisorBrokerBudgetExceeded,
    AdvisorBudget,
    AdvisorContextPack,
    AdvisorProtocolValidator,
    AdvisorResponse,
    StubAdvisorProvider,
)
from .batch_runner import BatchRunner, RunResult
from .model_gateway import (
    ModelCapability,
    ModelCapabilityRegistry,
    ModelGateway,
    ModelGatewayUnknownTier,
    ModelResponse,
    ModelTier,
    StubModelProvider,
    create_default_gateway,
    create_default_registry,
)
from .model_eval import (
    ControlledModelEvalHarness,
    ModelEvalCase,
    ModelEvalReport,
)
from .sampling import SamplingCandidate, SamplingReport, SamplingRunner
from .digest import BatchDigest, generate_batch_digest
from .orchestrator import OrchestrationResult, Stage1Orchestrator
from .artifact_gate import ArtifactCheck, ArtifactGate, ArtifactGateResult
from .quality_gate import QualityGateDecision, QualityGateManager
from .quality_digest import QualityDigest, QualityDigestGenerator, QualityDigestItem
from .evaluation import EvalCase, EvalSpec, EvaluationReport, EvaluationRunner
from .baseline import BaselineComparison, BaselineManager, BaselineRecord
from .trajectory import TrajectoryAnomaly, TrajectoryMonitor, TrajectoryReport
from .scoring import ArtifactScore, RunScore, ScoreComponent, ScoringEngine, TaskScore
from .routing import (
    RoutingExperimentManager,
    RoutingExperimentReport,
    RoutingExperimentResult,
    RoutingExperimentSpec,
    RoutingPolicy,
)
from .event_store import (
    EventStore,
    ReplayPreflightReport,
    ValidationIssue,
    ValidationReport,
    load_event_ids,
    replay_preflight,
    validate_jsonl_file,
)
from .event_schema import stable_idempotency_hash, validate_event
from .final_gate import FinalGateDecision, FinalGateRunner
from .kernel import Kernel
from .projection_store import (
    DependencyProjection,
    DependencyResolvedRecord,
    HandoffRecord,
    ProjectItemState,
    ProjectStateProjection,
    ProjectionBundle,
    TaskQueueProjection,
    replay_all,
    replay_dependency_state,
    replay_project_state,
    replay_task_queue_state,
)
from .project_board import (
    FinalGateResult,
    ProjectBoardItem,
    TransitionResult,
    check_allowed_files,
    complete_task_to_review,
    final_gate,
    transition_item,
)
from .task_queue import (
    HandoffResult,
    TaskQueueEntry,
    TaskTransitionResult,
    map_task_status_to_project_board,
    receive_handoff,
    transition_task,
)
from .task_records import (
    TaskRecordBundle,
    TaskRecordStore,
    TaskRecordValidationReport,
)
from .validators import (
    CANONICAL_FAILURE_CODES,
    ValidationResult,
    validate_advisor_protocol_events,
    validate_allowed_files_completeness,
    validate_approval_request,
    validate_completion_record,
    validate_events_schema,
    validate_failure_code,
    validate_handoff_pack,
    validate_replay_preflight_check,
)

__all__ = [
    "AdvisorBroker",
    "AdvisorBrokerBudgetExceeded",
    "AdvisorBudget",
    "AdvisorContextPack",
    "AdvisorProtocolValidator",
    "AdvisorResponse",
    "StubAdvisorProvider",
    "ArtifactCheck",
    "ControlledModelEvalHarness",
    "ModelCapability",
    "ModelCapabilityRegistry",
    "ModelEvalCase",
    "ModelEvalReport",
    "ModelGateway",
    "ModelGatewayUnknownTier",
    "ModelResponse",
    "ModelTier",
    "StubModelProvider",
    "create_default_gateway",
    "create_default_registry",
    "ArtifactGate",
    "ArtifactGateResult",
    "ArtifactScore",
    "BaselineComparison",
    "BaselineManager",
    "BaselineRecord",
    "BatchDigest",
    "BatchRunner",
    "DependencyProjection",
    "OrchestrationResult",
    "QualityDigest",
    "QualityDigestGenerator",
    "QualityDigestItem",
    "QualityGateDecision",
    "QualityGateManager",
    "RunScore",
    "RoutingExperimentManager",
    "RoutingExperimentReport",
    "RoutingExperimentResult",
    "RoutingExperimentSpec",
    "RoutingPolicy",
    "ScoreComponent",
    "ScoringEngine",
    "Stage1Orchestrator",
    "TaskScore",
    "TrajectoryAnomaly",
    "TrajectoryMonitor",
    "TrajectoryReport",
    "DependencyResolvedRecord",
    "EvalCase",
    "EvalSpec",
    "EvaluationReport",
    "EvaluationRunner",
    "EventStore",
    "FinalGateDecision",
    "FinalGateRunner",
    "FinalGateResult",
    "HandoffRecord",
    "HandoffResult",
    "Kernel",
    "ProjectItemState",
    "ProjectBoardItem",
    "ProjectStateProjection",
    "ProjectionBundle",
    "ReplayPreflightReport",
    "RunResult",
    "SamplingCandidate",
    "SamplingReport",
    "SamplingRunner",
    "TaskQueueProjection",
    "TaskQueueEntry",
    "TaskTransitionResult",
    "TaskRecordBundle",
    "TaskRecordStore",
    "TaskRecordValidationReport",
    "CANONICAL_FAILURE_CODES",
    "TransitionResult",
    "ValidationResult",
    "check_allowed_files",
    "complete_task_to_review",
    "final_gate",
    "generate_batch_digest",
    "ValidationIssue",
    "ValidationReport",
    "load_event_ids",
    "map_task_status_to_project_board",
    "receive_handoff",
    "replay_all",
    "replay_dependency_state",
    "replay_preflight",
    "replay_project_state",
    "replay_task_queue_state",
    "stable_idempotency_hash",
    "transition_item",
    "transition_task",
    "validate_advisor_protocol_events",
    "validate_allowed_files_completeness",
    "validate_approval_request",
    "validate_completion_record",
    "validate_events_schema",
    "validate_event",
    "validate_failure_code",
    "validate_handoff_pack",
    "validate_jsonl_file",
    "validate_replay_preflight_check",
]
