"""DocGenerator: auto-generated markdown documentation from Python source schemas."""

from __future__ import annotations

import ast
from pathlib import Path
from typing import Any


DOC_GENERATOR_SCHEMA_VERSION = "doc_generator.v1"


class DocGenerator:
    """Extract schema versions, dataclass fields, and docstrings from Python
    source files and generate clean markdown documentation.

    Uses only the ast module (stdlib) — reads source files, never modifies them.
    """

    def generate_module_docs(self, module_path: str | Path) -> str:
        """Generate markdown documentation for a single Python module.

        Extracts: module docstring, schema_version constants, and dataclass
        definitions with their fields and types.
        """
        path = Path(module_path)
        if not path.exists() or not path.suffix == ".py":
            return f"<!-- could not read {module_path} -->\n"

        source = path.read_text(encoding="utf-8")
        try:
            tree = ast.parse(source, filename=str(path))
        except SyntaxError as exc:
            return f"<!-- syntax error in {path.name}: {exc} -->\n"

        lines: list[str] = []
        module_doc = ast.get_docstring(tree)
        if module_doc:
            lines.append(f"# {path.stem}")
            lines.append("")
            lines.append(module_doc.strip())
            lines.append("")
        else:
            lines.append(f"# {path.stem}")
            lines.append("")

        schema_versions = _extract_schema_versions(tree)
        if schema_versions:
            lines.append("## Schema Versions")
            lines.append("")
            for name, value in schema_versions:
                lines.append(f"- `{name}`: `{value}`")
            lines.append("")

        dataclasses = _extract_dataclasses(tree)
        if dataclasses:
            lines.append("## Data Classes")
            lines.append("")
            for dc_name, dc_doc, fields in dataclasses:
                lines.append(f"### {dc_name}")
                lines.append("")
                if dc_doc:
                    lines.append(dc_doc.strip())
                    lines.append("")
                if fields:
                    lines.append("| Field | Type | Default |")
                    lines.append("|-------|------|---------|")
                    for fname, ftype, fdefault in fields:
                        lines.append(f"| `{fname}` | `{ftype}` | `{fdefault}` |")
                    lines.append("")

        return "\n".join(lines) + "\n"

    def generate_schema_registry(self, modules_dir: str | Path) -> str:
        """Generate a markdown table of all schema_version constants found
        across modules in a directory.
        """
        dir_path = Path(modules_dir)
        if not dir_path.is_dir():
            return f"<!-- directory not found: {modules_dir} -->\n"

        entries: list[tuple[str, str, str]] = []
        for py_file in sorted(dir_path.glob("*.py")):
            try:
                source = py_file.read_text(encoding="utf-8")
                tree = ast.parse(source, filename=str(py_file))
            except (SyntaxError, OSError):
                continue
            for name, value in _extract_schema_versions(tree):
                entries.append((py_file.stem, name, value))

        lines = ["# Schema Registry", ""]
        lines.append(f"> Auto-generated by DocGenerator `{DOC_GENERATOR_SCHEMA_VERSION}`")
        lines.append("")
        if entries:
            lines.append("| Module | Constant | Version |")
            lines.append("|--------|----------|---------|")
            for mod, name, ver in entries:
                lines.append(f"| `{mod}` | `{name}` | `{ver}` |")
        else:
            lines.append("No schema versions found.")
        lines.append("")
        return "\n".join(lines) + "\n"

    def generate_api_reference(self, module_path: str | Path) -> str:
        """Generate API reference markdown for a single module.

        Lists all public classes and functions with their signatures and
        docstrings.
        """
        path = Path(module_path)
        if not path.exists() or not path.suffix == ".py":
            return f"<!-- could not read {module_path} -->\n"

        source = path.read_text(encoding="utf-8")
        try:
            tree = ast.parse(source, filename=str(path))
        except SyntaxError as exc:
            return f"<!-- syntax error in {path.name}: {exc} -->\n"

        lines = [f"# API Reference: `{path.stem}`", ""]

        for node in ast.iter_child_nodes(tree):
            if isinstance(node, ast.ClassDef):
                doc = ast.get_docstring(node)
                lines.append(f"## class `{node.name}`")
                lines.append("")
                if doc:
                    lines.append(doc.strip())
                    lines.append("")
                for item in node.body:
                    if isinstance(item, ast.FunctionDef) and not item.name.startswith("_"):
                        sig = _format_signature(item)
                        method_doc = ast.get_docstring(item)
                        lines.append(f"### `{item.name}{sig}`")
                        lines.append("")
                        if method_doc:
                            lines.append(method_doc.strip())
                            lines.append("")

            elif isinstance(node, ast.FunctionDef) and not node.name.startswith("_"):
                sig = _format_signature(node)
                doc = ast.get_docstring(node)
                lines.append(f"## `{node.name}{sig}`")
                lines.append("")
                if doc:
                    lines.append(doc.strip())
                    lines.append("")

        if len(lines) <= 2:
            lines.append("No public API elements found.")
            lines.append("")

        return "\n".join(lines) + "\n"

    def save_docs(self, output_dir: str | Path) -> list[str]:
        """Generate documentation for all dispatch modules and save to output_dir.

        Returns the list of file paths written.
        """
        out = Path(output_dir)
        out.mkdir(parents=True, exist_ok=True)

        dispatch_dir = Path(__file__).parent / "dispatch"
        written: list[str] = []

        # Module docs
        modules_subdir = out / "modules"
        modules_subdir.mkdir(exist_ok=True)
        for py_file in sorted(dispatch_dir.glob("*.py")):
            md = self.generate_module_docs(py_file)
            dest = modules_subdir / f"{py_file.stem}.md"
            dest.write_text(md, encoding="utf-8")
            written.append(str(dest))

        # Schema registry
        registry_md = self.generate_schema_registry(dispatch_dir)
        registry_path = out / "SCHEMA_REGISTRY.md"
        registry_path.write_text(registry_md, encoding="utf-8")
        written.append(str(registry_path))

        # Top-level doc
        top_md_path = out / "DOC_GENERATOR.md"
        top_md_path.write_text(
            f"# Harness Documentation\n\n"
            f"> Auto-generated by DocGenerator `{DOC_GENERATOR_SCHEMA_VERSION}`\n\n"
            f"- [Schema Registry](SCHEMA_REGISTRY.md)\n"
            f"- [Module Docs](modules/)\n",
            encoding="utf-8",
        )
        written.append(str(top_md_path))

        return written


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------


def _extract_schema_versions(tree: ast.Module) -> list[tuple[str, str]]:
    results: list[tuple[str, str]] = []
    for node in ast.iter_child_nodes(tree):
        if isinstance(node, ast.Assign):
            for target in node.targets:
                if isinstance(target, ast.Name) and "SCHEMA_VERSION" in target.id:
                    value = _ast_constant_value(node.value)
                    if value is not None:
                        results.append((target.id, str(value)))
        elif isinstance(node, ast.AnnAssign):
            if isinstance(node.target, ast.Name) and "SCHEMA_VERSION" in node.target.id:
                value = _ast_constant_value(node.value) if node.value else None
                if value is not None:
                    results.append((node.target.id, str(value)))
    return results


def _extract_dataclasses(
    tree: ast.Module,
) -> list[tuple[str, str | None, list[tuple[str, str, str]]]]:
    results: list[tuple[str, str | None, list[tuple[str, str, str]]]] = []
    for node in ast.iter_child_nodes(tree):
        if not isinstance(node, ast.ClassDef):
            continue
        has_dataclass_decorator = any(
            (isinstance(d, ast.Name) and d.id == "dataclass")
            or (isinstance(d, ast.Attribute) and d.attr == "dataclass")
            or (isinstance(d, ast.Call) and (
                (isinstance(d.func, ast.Name) and d.func.id == "dataclass")
                or (isinstance(d.func, ast.Attribute) and d.func.attr == "dataclass")
            ))
            for d in node.decorator_list
        )
        if not has_dataclass_decorator:
            continue

        doc = ast.get_docstring(node)
        fields = _extract_class_fields(node)
        results.append((node.name, doc, fields))
    return results


def _extract_class_fields(
    cls_node: ast.ClassDef,
) -> list[tuple[str, str, str]]:
    fields: list[tuple[str, str, str]] = []
    for item in cls_node.body:
        if isinstance(item, ast.AnnAssign) and isinstance(item.target, ast.Name):
            fname = item.target.id
            ftype = _simplify_type_hint(item.annotation) if item.annotation else ""
            if item.value is not None:
                fdefault = ast.dump(item.value)
            else:
                fdefault = ""
            fields.append((fname, ftype, fdefault))
    return fields


def _simplify_type_hint(node: ast.expr | None) -> str:
    if node is None:
        return ""
    try:
        return ast.unparse(node)
    except Exception:
        return ast.dump(node)


def _ast_constant_value(node: ast.expr) -> str | None:
    if isinstance(node, ast.Constant) and isinstance(node.value, str):
        return node.value
    return None


def _format_signature(func_node: ast.FunctionDef) -> str:
    args = func_node.args
    parts: list[str] = []

    defaults_offset = len(args.args) - len(args.defaults)
    for i, arg in enumerate(args.args):
        if arg.arg == "self" or arg.arg == "cls":
            continue
        part = arg.arg
        if arg.annotation:
            part += f": {_simplify_type_hint(arg.annotation)}"
        di = i - defaults_offset
        if di >= 0 and di < len(args.defaults):
            part += f" = {_simplify_type_hint(args.defaults[di])}"
        parts.append(part)

    if args.vararg:
        parts.append(f"*{_simplify_type_hint(args.vararg.annotation) or ''}")
    if args.kwarg:
        parts.append(f"**{_simplify_type_hint(args.kwarg.annotation) or ''}")

    return f"({', '.join(parts)})"
