#!/usr/bin/env python3
"""Real Pilot 1: one-command local real patch/branch production.

Starts a local engine, creates a real temporary git target repo with a bare
remote, drives the guarded V2 output API, executes an idempotent command in an
app-owned git worktree, captures/approves/exports the patch, and pushes an
``acp/*`` branch to the local test remote.

Usage:
    uv run --no-project python scripts/real_pilot_1.py
"""

from __future__ import annotations

import argparse
import json
import os
import random
import signal
import subprocess
import sys
import tempfile
import time
from pathlib import Path
from typing import Any


ADMIN_ACTOR = "real-pilot-1"
DEFAULT_HEALTH_TIMEOUT_SECONDS = 180
WORKER_SOURCE = """\
from pathlib import Path

readme = Path("README.md")
content = readme.read_text(encoding="utf-8")
marker = "## Real Pilot 1\\n\\nThis line was written by ACP command executor in an app-owned git worktree.\\n"
if "## Real Pilot 1" not in content:
    readme.write_text(content.rstrip() + "\\n\\n" + marker, encoding="utf-8")

Path("pilot_evidence.txt").write_text(
    "real pilot artifact generated by ACP command executor\\n",
    encoding="utf-8",
)
print("real-pilot-worker wrote README.md and pilot_evidence.txt")
"""


class PilotError(RuntimeError):
    pass


class ApiClient:
    def __init__(self, base_url: str) -> None:
        self.base_url = base_url.rstrip("/")

    def call(self, method: str, path: str, body: dict[str, Any] | None = None) -> dict[str, Any]:
        cmd = [
            "curl",
            "-fsS",
            "--max-time",
            "30",
            "-X",
            method,
            "-H",
            "Content-Type: application/json",
        ]
        if body is not None:
            cmd.extend(["--data-binary", json.dumps(body)])
        cmd.append(f"{self.base_url}{path}")
        result = subprocess.run(cmd, text=True, capture_output=True, check=False)
        if result.returncode != 0:
            raise PilotError(
                f"HTTP call failed: {method} {path}\nstdout:\n{result.stdout}\nstderr:\n{result.stderr}"
            )
        return json.loads(result.stdout) if result.stdout else {}

    def wait_for_health(self, timeout_seconds: int) -> None:
        deadline = time.time() + timeout_seconds
        last_error = "not attempted"
        while time.time() < deadline:
            result = subprocess.run(
                ["curl", "-fsS", "--max-time", "3", f"{self.base_url}/api/v1/health"],
                text=True,
                capture_output=True,
                check=False,
            )
            if result.returncode == 0:
                return
            last_error = result.stderr.strip() or result.stdout.strip()
            time.sleep(1)
        raise PilotError(f"engine did not become healthy: {last_error}")


def run(cmd: list[str], cwd: Path | None = None) -> str:
    result = subprocess.run(cmd, cwd=cwd, text=True, capture_output=True, check=False)
    if result.returncode != 0:
        raise PilotError(
            f"command failed: {' '.join(cmd)}\nstdout:\n{result.stdout}\nstderr:\n{result.stderr}"
        )
    return result.stdout.strip()


def pick_port() -> int:
    return random.randint(20000, 50000)


def repo_root() -> Path:
    return Path(__file__).resolve().parents[1]


def create_target_repo(root: Path) -> tuple[Path, Path, str]:
    target = root / "target-repo"
    remote = root / "target-remote.git"
    target.mkdir()
    run(["git", "init", "-b", "main"], cwd=target)
    run(["git", "config", "user.name", "Real Pilot 1"], cwd=target)
    run(["git", "config", "user.email", "real-pilot-1@example.invalid"], cwd=target)
    (target / "README.md").write_text("# Real Pilot Target\n\nBase target repo.\n", encoding="utf-8")
    run(["git", "add", "README.md"], cwd=target)
    run(["git", "commit", "-m", "base"], cwd=target)
    run(["git", "init", "--bare", str(remote)])
    run(["git", "symbolic-ref", "HEAD", "refs/heads/main"], cwd=remote)
    run(["git", "remote", "add", "origin", str(remote)], cwd=target)
    run(["git", "push", "-u", "origin", "main"], cwd=target)
    source_revision = run(["git", "rev-parse", "HEAD"], cwd=target)
    return target, remote, source_revision


def start_engine(args: argparse.Namespace, root: Path, run_root: Path) -> subprocess.Popen[str] | None:
    if args.reuse_engine:
        return None

    log_path = run_root / "engine.log"
    env = os.environ.copy()
    env.update(
        {
            "HOST": "127.0.0.1",
            "PORT": str(args.port),
            "ACP_DB_PATH": str(run_root / "control-plane" / "local-team.db"),
            "ACP_DASHBOARD_DIR": str(root / "dashboard" / "out"),
            "ACP_ENABLE_TARGET_REPO_OUTPUT": "1",
            "ACP_TARGET_REPO_ALLOW_LOCAL_REMOTE": "1",
            "ACP_TARGET_REPO_REMOTE_ALLOWLIST": "origin",
        }
    )
    env.pop("ACP_REQUIRE_AUTH", None)
    env.pop("ACP_ADMIN_API_KEY", None)
    env.pop("ACP_ENABLE_PROVIDER_EXECUTION", None)
    env.pop("ACP_ENABLE_CLI_EXECUTION", None)
    (run_root / "control-plane").mkdir()
    log_file = log_path.open("w", encoding="utf-8")
    process = subprocess.Popen(
        ["cargo", "run", "-p", "engine"],
        cwd=root,
        env=env,
        stdout=log_file,
        stderr=subprocess.STDOUT,
        text=True,
        start_new_session=True,
    )
    return process


def stop_engine(process: subprocess.Popen[str] | None, keep_engine: bool) -> None:
    if process is None or keep_engine:
        return
    if process.poll() is not None:
        return
    os.killpg(process.pid, signal.SIGTERM)
    try:
        process.wait(timeout=10)
    except subprocess.TimeoutExpired:
        os.killpg(process.pid, signal.SIGKILL)
        process.wait(timeout=10)


def require_key(payload: dict[str, Any], *path: str) -> Any:
    current: Any = payload
    for key in path:
        if not isinstance(current, dict) or key not in current:
            raise PilotError(f"missing response field: {'.'.join(path)} in {payload}")
        current = current[key]
    return current


def tick_until_completed(api: ApiClient, run_id: str, worker_path: Path) -> dict[str, Any]:
    command = f"python3 {worker_path}"
    for _ in range(12):
        tick = api.call(
            "POST",
            f"/api/v1/workflow-runs/{run_id}/tick",
            {
                "actor": ADMIN_ACTOR,
                "executor": "command",
                "command": command,
                "timeout_ms": 30000,
            },
        )
        status = require_key(tick, "tick", "result", "status")
        action = require_key(tick, "tick", "action")
        run_detail = api.call("GET", f"/api/v1/workflow-runs/{run_id}")
        run = require_key(run_detail, "run")
        if run.get("status") == "completed":
            return {"tick": tick, "run": run}
        if status == "failed" or action == "failed":
            raise PilotError(f"workflow tick failed: {tick}")
    raise PilotError("workflow did not complete after 12 ticks")


def write_summary(path: Path, summary: dict[str, Any]) -> None:
    path.write_text(json.dumps(summary, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description="Run Real Pilot 1 against a real local git repo.")
    parser.add_argument("--port", type=int, default=0, help="local engine port; default picks a free port")
    parser.add_argument("--base-url", help="reuse a running engine at this URL")
    parser.add_argument("--reuse-engine", action="store_true", help="do not start or stop engine")
    parser.add_argument("--keep-engine", action="store_true", help="leave started engine running")
    parser.add_argument("--run-root", type=Path, help="evidence directory; default creates /tmp/acp-real-pilot-1-*")
    parser.add_argument("--health-timeout", type=int, default=DEFAULT_HEALTH_TIMEOUT_SECONDS)
    args = parser.parse_args()
    if args.base_url:
        args.reuse_engine = True
    if args.reuse_engine and not args.base_url and args.port == 0:
        args.port = 8080

    root = repo_root()
    run_root = args.run_root or Path(tempfile.mkdtemp(prefix="acp-real-pilot-1-"))
    run_root.mkdir(parents=True, exist_ok=True)
    args.port = args.port or pick_port()
    base_url = args.base_url or f"http://127.0.0.1:{args.port}"
    api = ApiClient(base_url)
    worker_path = run_root / "real_pilot_worker.py"
    worker_path.write_text(WORKER_SOURCE, encoding="utf-8")

    process: subprocess.Popen[str] | None = None
    try:
        print("=== Real Pilot 1 ===")
        print(f"run_root={run_root}")
        print(f"api={base_url}")
        print(f"dashboard={base_url}/")
        print("provider_execution=off")
        print("cli_execution=off")
        print("target_output=on local-remote-only")

        target, remote, source_revision = create_target_repo(run_root)
        main_before = run(["git", "rev-parse", "main"], cwd=target)
        print(f"target_repo={target}")
        print(f"test_remote={remote}")
        print(f"source_revision={source_revision}")

        process = start_engine(args, root, run_root)
        api.wait_for_health(args.health_timeout)
        if process is not None and process.poll() is not None:
            raise PilotError(f"engine exited early; see {run_root / 'engine.log'}")

        plan = api.call(
            "POST",
            "/api/v1/plans",
            {
                "raw_request": "Real Pilot 1: add local evidence to a target repository.",
                "request_source": "real-pilot-1",
            },
        )
        plan_id = require_key(plan, "plan", "plan_id")
        run_response = api.call("POST", "/api/v1/workflow-runs", {"plan_id": plan_id})
        run_id = require_key(run_response, "run", "run_id")
        print(f"plan_id={plan_id}")
        print(f"run_id={run_id}")

        workspace_response = api.call(
            "POST",
            "/api/v1/supervised-patch/workspaces",
            {
                "run_id": run_id,
                "plan_id": plan_id,
                "target_id": "real-pilot-1-target",
                "target_repo_path": str(target),
                "source_revision": source_revision,
                "workspace_mode": "git_worktree",
            },
        )
        workspace = require_key(workspace_response, "workspace")
        workspace_id = workspace["workspace_id"]
        workspace_path = Path(workspace["workspace_path"])
        actual_source_revision = workspace["source_revision"]
        print(f"workspace_id={workspace_id}")
        print(f"workspace_path={workspace_path}")

        tick_result = tick_until_completed(api, run_id, worker_path)
        if "## Real Pilot 1" not in (workspace_path / "README.md").read_text(encoding="utf-8"):
            raise PilotError("executor did not update README.md in workspace")
        if not (workspace_path / "pilot_evidence.txt").exists():
            raise PilotError("executor did not create pilot_evidence.txt in workspace")
        print(f"workflow_status={tick_result['run']['status']}")

        capture = api.call("POST", f"/api/v1/supervised-patch/workspaces/{workspace_id}/capture")
        artifact = require_key(capture, "artifact")
        artifact_id = artifact["artifact_id"]
        patch_hash = artifact["patch_hash"]
        changed_files = artifact["changed_files"]
        evidence_status = artifact["evidence_bundle"]["verification"]["status"]
        if evidence_status != "evidence_recorded":
            raise PilotError(f"verification evidence not ready: {artifact['evidence_bundle']}")
        if artifact["secret_scan_status"] != "passed" or artifact["redaction_status"] != "redacted":
            raise PilotError(f"artifact not export-safe: {artifact}")
        print(f"artifact_id={artifact_id}")
        print(f"patch_hash={patch_hash}")
        print(f"changed_files={','.join(changed_files)}")
        print(f"verification={evidence_status}")

        approval = api.call(
            "POST",
            f"/api/v1/workflow-runs/{run_id}/approvals",
            {
                "node_id": "real-pilot-1-approval",
                "decision": "approved",
                "reason": "real pilot evidence reviewed by local pilot script",
                "bound_patch_hash": patch_hash,
                "bound_source_revision": actual_source_revision,
                "bound_changed_files": changed_files,
                "expires_at": "2099-12-31T23:59:59Z",
            },
        )
        approval_id = require_key(approval, "approval", "approval_id")
        print(f"approval_id={approval_id}")

        export = api.call("POST", f"/api/v1/supervised-patch/artifacts/{artifact_id}/export", {"run_id": run_id})
        if not export["export"]["integrity"]["integrity_ok"]:
            raise PilotError(f"artifact integrity failed: {export}")

        patch_output = api.call(
            "POST",
            f"/api/v1/supervised-patch/artifacts/{artifact_id}/output",
            {"run_id": run_id, "mode": "export_patch", "confirm_target_output": True},
        )
        patch_text = patch_output["output"]["patch"]
        patch_path = run_root / f"{artifact_id}.patch"
        patch_path.write_text(patch_text, encoding="utf-8")
        print(f"patch_file={patch_path}")

        branch_name = f"acp/{artifact_id}"
        push = api.call(
            "POST",
            f"/api/v1/supervised-patch/artifacts/{artifact_id}/output",
            {
                "run_id": run_id,
                "mode": "push_branch",
                "confirm_target_output": True,
                "branch_name": branch_name,
                "remote": "origin",
                "commit_message": "feat: add real pilot evidence",
                "pr_title": "Add real pilot evidence",
            },
        )
        output = push["output"]
        remote_commit = run(["git", "rev-parse", f"refs/heads/{branch_name}"], cwd=remote)
        main_after = run(["git", "rev-parse", "main"], cwd=target)
        if main_after != main_before:
            raise PilotError("target main changed; this violates Real Pilot 1 boundary")
        if remote_commit != output["commit_sha"]:
            raise PilotError("remote acp branch commit mismatch")

        summary = {
            "api": base_url,
            "dashboard": f"{base_url}/",
            "target_repo": str(target),
            "test_remote": str(remote),
            "main_before": main_before,
            "main_after": main_after,
            "plan_id": plan_id,
            "run_id": run_id,
            "workspace_id": workspace_id,
            "workspace_path": str(workspace_path),
            "artifact_id": artifact_id,
            "patch_hash": patch_hash,
            "changed_files": changed_files,
            "approval_id": approval_id,
            "patch_file": str(patch_path),
            "branch_name": branch_name,
            "branch_commit": output["commit_sha"],
            "engine_log": str(run_root / "engine.log"),
            "rollback": f"git -C {remote} update-ref -d refs/heads/{branch_name}",
        }
        summary_path = run_root / "real-pilot-1-summary.json"
        write_summary(summary_path, summary)

        print("=== Real Pilot 1 COMPLETE ===")
        print(f"branch={branch_name}")
        print(f"branch_commit={output['commit_sha']}")
        print(f"target_main_unchanged={main_after == main_before}")
        print(f"summary={summary_path}")
        print("next_commands:")
        print(f"  git -C {remote} show --stat {branch_name}")
        print(f"  git -C {target} status --short --branch")
        print(f"  git -C {remote} update-ref -d refs/heads/{branch_name}")
        if args.keep_engine and process is not None:
            print(f"engine_pid={process.pid}")
            print(f"engine_log={run_root / 'engine.log'}")
        return 0
    except PilotError as error:
        print(f"FAIL: {error}", file=sys.stderr)
        if run_root.exists():
            print(f"evidence_dir={run_root}", file=sys.stderr)
        return 1
    finally:
        stop_engine(process, args.keep_engine)


if __name__ == "__main__":
    sys.exit(main())
