"""Configuration generator and trust manager for Codex Lifecycle Hooks.

Generates the TOML configuration block linking Codex hook events to the
dispatcher, establishes cryptographically verified trusted_hash entries,
and avoids unsafe flags like --dangerously-bypass-hook-trust in production.
"""

from __future__ import annotations

import hashlib
import os
from pathlib import Path
from typing import Mapping


DEFAULT_HOOK_EVENTS = (
    "SessionStart",
    "PreCompact",
    "PostCompact",
    "PreToolUse",
    "PostToolUse",
    "PermissionRequest",
    "Stop",
)


def compute_bundle_hash(dispatcher_path: Path | str, hook_dir: Path | str | None = None) -> str:
    """Compute deterministic SHA256 digest of dispatcher and hook package files."""
    hasher = hashlib.sha256()
    disp = Path(dispatcher_path).resolve()
    if disp.is_file():
        hasher.update(disp.read_bytes())
    if hook_dir is not None:
        h_dir = Path(hook_dir).resolve()
        if h_dir.is_dir():
            for py_file in sorted(h_dir.glob("*.py")):
                hasher.update(py_file.name.encode("utf-8"))
                hasher.update(py_file.read_bytes())
    return hasher.hexdigest()


class HookConfigGenerator:
    """Generates TOML configuration and trust hashes for Codex Lifecycle Hooks."""

    def __init__(
        self,
        dispatcher_path: Path | str,
        *,
        worktree_path: Path | str | None = None,
        python_executable: str = "/usr/bin/python3",
        timeout_seconds: int = 30,
        hook_events: tuple[str, ...] = DEFAULT_HOOK_EVENTS,
    ):
        self.dispatcher_path = Path(dispatcher_path).resolve()
        self.worktree_path = Path(worktree_path).resolve() if worktree_path else None
        self.python_executable = python_executable
        self.timeout_seconds = timeout_seconds
        self.hook_events = hook_events

    def generate_toml(self, trusted_hash: str | None = None) -> str:
        """Produce valid TOML string configuring hooks and trust state."""
        digest = trusted_hash or compute_bundle_hash(self.dispatcher_path, self.dispatcher_path.parent)

        lines: list[str] = [
            "# Generated by Codex Lifecycle Hooks Control Plane",
            "[features]",
            "hooks = true",
            "",
            "[hooks]",
        ]

        # Configure event matchers
        for event in self.hook_events:
            cmd = f"{self.python_executable} {self.dispatcher_path} {event}"
            lines.extend([
                f"{event} = [",
                '  { matcher = "*", hooks = [',
                f'    {{ type = "command", command = "{cmd}", timeout = {self.timeout_seconds} }}',
                "  ] }",
                "]",
            ])

        # Configure trust state
        lines.extend([
            "",
            f'[hooks.state."{self.dispatcher_path}"]',
            "enabled = true",
            f'trusted_hash = "{digest}"',
        ])

        if self.worktree_path is not None:
            lines.extend([
                "",
                f'[projects."{self.worktree_path}"]',
                'trust_level = "trusted"',
                f'trusted_hash = "{digest}"',
            ])

        lines.append("")
        return "\n".join(lines)

    def write_config(self, target_path: Path | str, trusted_hash: str | None = None) -> Path:
        """Write generated configuration to destination file."""
        target = Path(target_path)
        target.parent.mkdir(parents=True, exist_ok=True)
        content = self.generate_toml(trusted_hash=trusted_hash)
        target.write_text(content, encoding="utf-8")
        return target
