// Generated by codegen/generate_wire_types.py. DO NOT EDIT.

use serde::{Deserialize, Serialize};
use serde_json::Value;

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum RequestSource {
    Cli,
    Api,
    Dashboard,
    Agent,
    Workflow,
    TestFixture,
}

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum ModelTier {
    CheapExecutor,
    BalancedWorker,
    StrongPlanner,
    Verifier,
    Advisor,
}

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum TaskDomain {
    Code,
    Docs,
    Config,
    Infra,
    Math,
    Architecture,
    RepoOps,
    Governance,
    Other,
}

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum TaskIntent {
    Generate,
    Review,
    Debug,
    Summarize,
    Audit,
    Plan,
    Refactor,
    Compare,
    Explain,
    Classify,
}

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum RiskFlag {
    TargetWrite,
    ProviderCall,
    SandboxExecution,
    Deployment,
    SecretHandling,
    DestructiveOperation,
    LongContext,
    HighUncertainty,
}

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum QualityRequirement {
    Draft,
    Standard,
    High,
    Critical,
}

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum RiskLevel {
    Low,
    Medium,
    High,
    Critical,
}

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum ConfidenceLabel {
    Low,
    Medium,
    High,
}

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum EvidencePolarity {
    Positive,
    Negative,
}

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum EvidenceSource {
    RawRequest,
    RepoContext,
    UserConstraints,
    TargetMetadata,
}

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum ExpectedQualityBand {
    Low,
    Medium,
    High,
    Unknown,
}

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum DecisionStatus {
    Decided,
    NeedsApproval,
    Blocked,
    DiagnosticOnly,
}

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum GateSeverity {
    Info,
    Warning,
    Block,
    Critical,
}

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum ExecutorType {
    Noop,
    Mock,
    Manual,
    Provider,
    ClaudeCodeCli,
    CodexCli,
}

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum ExecutionStatus {
    NotExecuted,
    PreviewGenerated,
    MockCompleted,
    ManualPending,
    ManualCompleted,
    Failed,
    CliCompleted,
    ProviderCompleted,
}

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum EvaluationStatus {
    Pass,
    Fail,
    NeedsHumanReview,
    NotEvaluated,
}

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum CheckStatus {
    Pass,
    Fail,
    Warning,
    Skipped,
}

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum FinalStatus {
    Dispatched,
    Executing,
    Completed,
    Failed,
    Escalated,
    Cancelled,
    NotExecuted,
    ManualPending,
}

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq)]
pub struct Evidence {
    pub feature: String,
    pub text: String,
    pub span: (i64, i64),
    pub polarity: EvidencePolarity,
    pub source: EvidenceSource,
    pub rule_id: Option<String>,
    pub confidence: f64,
    pub negation_scope: Option<String>,
}

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq)]
pub struct TaskAnalysis {
    pub schema_version: String,
    pub analysis_id: String,
    pub raw_request_snapshot: String,
    pub request_source: RequestSource,
    pub primary_task_type: String,
    pub task_domain: TaskDomain,
    pub task_intent: TaskIntent,
    pub risk_flags: Vec<RiskFlag>,
    pub complexity_score: f64,
    pub cognitive_complexity: f64,
    pub context_complexity: f64,
    pub execution_risk: f64,
    pub ambiguity_score: f64,
    pub required_capabilities: Vec<String>,
    pub context_budget_estimate: i64,
    pub execution_budget_estimate: i64,
    pub quality_requirement: QualityRequirement,
    pub risk_level: RiskLevel,
    pub confidence: f64,
    pub confidence_label: ConfidenceLabel,
    pub uncertainty_reason: Vec<String>,
    pub safe_default: String,
    pub escalation_trigger: Option<String>,
    pub positive_evidence: Vec<Evidence>,
    pub negative_evidence: Vec<Evidence>,
    pub features_detected: Value,
    pub analysis_method: String,
    pub created_at: String,
}

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq)]
pub struct BudgetReservation {
    pub schema_version: String,
    pub reservation_id: String,
    pub decision_id: String,
    pub currency: String,
    pub pricing_snapshot_id: Option<String>,
    pub pre_budget: i64,
    pub reserved_input_tokens: i64,
    pub reserved_output_tokens: i64,
    pub reserved_total_tokens: i64,
    pub reserved_cost: f64,
    pub budget_policy_id: Option<String>,
    pub budget_gate: Option<String>,
    pub status: String,
    pub actual_usage_ref: Option<String>,
    pub budget_delta: Option<i64>,
    pub budget_violation: bool,
    pub created_at: String,
    pub updated_at: String,
    pub expires_at: Option<String>,
}

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq)]
pub struct ExecutionGate {
    pub gate_id: String,
    pub gate_type: String,
    pub severity: GateSeverity,
    pub reason: String,
    pub evidence_refs: Vec<String>,
    pub clearance_required: String,
    pub cleared: bool,
    pub cleared_by: Option<String>,
    pub cleared_at: Option<String>,
}

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq)]
pub struct ShadowRoute {
    pub tier: ModelTier,
    pub profile_id: Option<String>,
    pub reason: String,
    pub admission_scope: String,
    pub estimated_cost: Option<f64>,
    pub expected_tradeoff: String,
}

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq)]
pub struct RejectedCandidate {
    pub tier: ModelTier,
    pub profile_id: Option<String>,
    pub reason: String,
    pub constraint_failed: Option<String>,
    pub estimated_cost: Option<f64>,
}

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq)]
pub struct DispatchDecision {
    pub schema_version: String,
    pub decision_id: String,
    pub analysis_id: String,
    pub analysis_snapshot: Value,
    pub selected_tier: ModelTier,
    pub selected_profile_id: Option<String>,
    pub fallback_tier: ModelTier,
    pub fallback_profile_id: Option<String>,
    pub shadow_routes: Vec<ShadowRoute>,
    pub hard_constraints: Vec<String>,
    pub rejected_candidates: Vec<RejectedCandidate>,
    pub no_shadow_route_reason: Option<String>,
    pub max_input_tokens: i64,
    pub max_output_tokens: i64,
    pub routing_reason: String,
    pub quality_requirement: QualityRequirement,
    pub expected_quality_band: ExpectedQualityBand,
    pub confidence: f64,
    pub confidence_label: ConfidenceLabel,
    pub budget_reservation: BudgetReservation,
    pub execution_policy: Value,
    pub execution_gates: Vec<ExecutionGate>,
    pub routing_mode: String,
    pub routing_experiment_id: Option<String>,
    pub decision_status: DecisionStatus,
    pub created_at: String,
}

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq)]
pub struct ExecutionResult {
    pub schema_version: String,
    pub result_id: String,
    pub dispatch_id: String,
    pub decision_id: String,
    pub executor_type: ExecutorType,
    pub status: ExecutionStatus,
    pub output: Option<String>,
    pub prompt_pack: Option<Value>,
    pub input_tokens: Option<i64>,
    pub output_tokens: Option<i64>,
    pub estimated_cost: Option<f64>,
    pub latency_ms: Option<i64>,
    pub error_domain: Option<String>,
    pub error_message: Option<String>,
    pub provider_request_id: Option<String>,
    pub attempt_number: Option<i64>,
    pub finish_reason: Option<String>,
    pub usage_source: Option<String>,
    pub created_at: String,
}

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq)]
pub struct EvaluationCheck {
    pub check_id: String,
    pub name: String,
    pub status: CheckStatus,
    pub reason: String,
}

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq)]
pub struct EvaluationResult {
    pub schema_version: String,
    pub evaluation_id: String,
    pub dispatch_id: String,
    pub decision_id: String,
    pub execution_result_id: String,
    pub status: EvaluationStatus,
    pub checks: Vec<EvaluationCheck>,
    pub quality_score: Option<f64>,
    pub requires_retry: bool,
    pub retry_reason: Option<String>,
    pub created_at: String,
}

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq)]
pub struct DispatchRecord {
    pub schema_version: String,
    pub dispatch_id: String,
    pub request_snapshot: String,
    pub task_analysis_id: String,
    pub decision_id: String,
    pub execution_result_id: Option<String>,
    pub evaluation_result_id: Option<String>,
    pub usage_ledger_row_id: Option<String>,
    pub budget_reservation_id: Option<String>,
    pub final_status: FinalStatus,
    pub created_at: String,
    pub updated_at: String,
}

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq)]
pub struct DispatchBundle {
    pub record: DispatchRecord,
    pub analysis: TaskAnalysis,
    pub decision: DispatchDecision,
    pub execution_result: ExecutionResult,
    pub evaluation_result: EvaluationResult,
}

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq)]
pub struct DispatchRequest {
    pub schema_version: String,
    pub raw_request: String,
    pub request_source: RequestSource,
}

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq)]
pub struct DispatchBundleValue {
    pub record: Value,
    pub analysis: Value,
    pub decision: Value,
    pub execution_result: Value,
    pub evaluation_result: Value,
}

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq)]
pub struct ApiStatus {
    pub schema_version: String,
    pub status: String,
    pub tenant_id: Option<String>,
}
